[package]
name = "ruffle_web_common"
version = "0.1.0"
authors = ["Ruffle LLC <ruffle@ruffle.rs>"]
edition.workspace = true
license = "MIT OR Apache-2.0"

[lints]
workspace = true

[dependencies]
js-sys = { workspace = true }
tracing = { workspace = true }
wasm-bindgen = { workspace = true }

[dependencies.web-sys]
version = "0.3.69"
features = ["Window"]
